# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: KevinMarquette
# Generated on: 2/25/2018

@{
    RootModule        = 'Select-Ast.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = 'bb2ddc89-4d05-4fe3-bdac-7379386f40cd'
    Author            = 'KevinMarquette'
    CompanyName       = 'Unknown'
    Copyright         = '(c) KevinMarquette. All rights reserved.'
    Description       = ''
    FunctionsToExport = @()
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

