# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: KevinMarquette
# Generated on: 2/25/2018

@{
    RootModule        = 'Select-Ast.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = 'bb2ddc89-4d05-4fe3-bdac-7379386f40cd'
    Author            = 'Kevin Marquette'
    CompanyName       = 'Unknown'
    Copyright         = '(c) 2018 KevinMarquette. All rights reserved.'
    Description       = 'A PowerShell module for working with the AST'
    FunctionsToExport = @('Select-Ast')
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            Tags       = @('AST')
            LicenseUri = 'https://github.com/KevinMarquette/Select-Ast/blob/master/LICENSE'
            ProjectUri = 'https://github.com/KevinMarquette/Select-Ast  '
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

